//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppinstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public int ProductId { get; set; }
        public string UserId { get; set; }
        public int ShippingID { get; set; }
        public Nullable<int> TotalCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
